/**
 * Companion code generators.
 *
 * When a platform cannot be reached directly from the browser — Google
 * Workspace OAuth is unavailable, or a service-role key must not leave the
 * server — Bernie generates code you deploy *on that platform* instead. The
 * deployment exposes one HTTPS endpoint that Bernie's Custom HTTP Saves
 * connection can pull from and push to, so a workflow keeps working without
 * the blocked credential path.
 *
 * Pure string building, no side effects, so every generator is unit testable.
 */

export type CompanionTarget = 'sheets-apps-script' | 'supabase-edge-function' | 'drive-apps-script';

export interface CompanionFile {
  name: string;
  language: 'javascript' | 'typescript' | 'json' | 'sql';
  contents: string;
}

export interface CompanionBundle {
  target: CompanionTarget;
  title: string;
  /** What this deployment does, in one line. */
  summary: string;
  /** Ordered steps the user follows to deploy it. */
  steps: string[];
  files: CompanionFile[];
  /** How to point Bernie at the deployment once it exists. */
  wireUp: string[];
}

export interface CompanionOptions {
  /** Spreadsheet the Apps Script should bind to. */
  spreadsheetId?: string;
  /** Default tab name. */
  sheetName?: string;
  /** Drive folder the script should read and write. */
  folderId?: string;
  /** Supabase table an Edge Function should write to. */
  table?: string;
  /** Conflict column for upserts. */
  onConflict?: string;
  /** Shared secret the endpoint requires. Generated when absent. */
  sharedSecret?: string;
}

/**
 * A URL-safe shared secret. Uses the Web Crypto API when available so the
 * value is not predictable, and never silently falls back to Math.random
 * without saying so in the generated comment.
 */
export function generateSharedSecret(length = 32): string {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const crypto = (globalThis as any).crypto;

  if (crypto?.getRandomValues) {
    const bytes = new Uint8Array(length);
    crypto.getRandomValues(bytes);
    return Array.from(bytes, (byte) => alphabet[byte % alphabet.length]).join('');
  }

  let out = '';
  for (let i = 0; i < length; i += 1) {
    out += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return out;
}

function secretOf(options: CompanionOptions): string {
  return String(options.sharedSecret || '').trim() || generateSharedSecret();
}

/* -------------------------------------------------------------------------- */
/* Google Sheets, via Apps Script                                             */
/* -------------------------------------------------------------------------- */

function sheetsAppsScript(options: CompanionOptions, secret: string): string {
  const sheetName = options.sheetName || 'Sheet1';
  const spreadsheetId = options.spreadsheetId || '';

  return `/**
 * Bernie companion endpoint for Google Sheets.
 *
 * Deployed as a Web App, this gives Bernie a token-free way to read and write
 * this spreadsheet: Apps Script already runs as you, so no OAuth handshake and
 * no Google API key are involved.
 *
 * Generated by Bernie. Safe to edit.
 */

// Bernie must send this in the "secret" field. Rotate it by changing both here
// and in the Bernie connection.
var BERNIE_SECRET = ${JSON.stringify(secret)};

${spreadsheetId ? `// Bound spreadsheet. Leave blank to use the one this script is attached to.
var SPREADSHEET_ID = ${JSON.stringify(spreadsheetId)};` : `// Blank means "the spreadsheet this script is attached to".
var SPREADSHEET_ID = '';`}
var DEFAULT_SHEET = ${JSON.stringify(sheetName)};

function openSheet_(name) {
  var book = SPREADSHEET_ID
    ? SpreadsheetApp.openById(SPREADSHEET_ID)
    : SpreadsheetApp.getActiveSpreadsheet();
  if (!book) {
    throw new Error('No spreadsheet. Set SPREADSHEET_ID, or bind this script to a sheet.');
  }

  var sheet = book.getSheetByName(name || DEFAULT_SHEET);
  if (!sheet) {
    sheet = book.insertSheet(name || DEFAULT_SHEET);
  }
  return sheet;
}

function json_(payload, status) {
  return ContentService
    .createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}

function authorize_(params) {
  if (!BERNIE_SECRET) return;
  if (String(params && params.secret) !== BERNIE_SECRET) {
    throw new Error('Unauthorized: the shared secret did not match.');
  }
}

/** Rows out of the sheet, using the header row for keys. */
function readRows_(sheetName, limit) {
  var sheet = openSheet_(sheetName);
  var values = sheet.getDataRange().getValues();
  if (!values.length) return [];

  var headers = values[0].map(function (header, index) {
    var name = String(header || '').trim();
    return name || 'col_' + (index + 1);
  });

  var rows = [];
  var max = limit ? Math.min(Number(limit) + 1, values.length) : values.length;
  for (var i = 1; i < max; i++) {
    var row = {};
    for (var c = 0; c < headers.length; c++) {
      row[headers[c]] = values[i][c];
    }
    rows.push(row);
  }
  return rows;
}

/** Turns rows into a rectangular matrix, header row first. */
function toMatrix_(rows, includeHeaders) {
  if (!rows.length) return [];

  var headers = [];
  rows.forEach(function (row) {
    Object.keys(row).forEach(function (key) {
      if (headers.indexOf(key) === -1) headers.push(key);
    });
  });

  var matrix = includeHeaders === false ? [] : [headers];
  rows.forEach(function (row) {
    matrix.push(headers.map(function (header) {
      var value = row[header];
      if (value === null || value === undefined) return '';
      return typeof value === 'object' ? JSON.stringify(value) : value;
    }));
  });
  return matrix;
}

/**
 * GET pulls rows.
 *   ?secret=...&sheet=Sheet1&limit=10
 */
function doGet(e) {
  try {
    var params = (e && e.parameter) || {};
    authorize_(params);
    var rows = readRows_(params.sheet, params.limit);
    return json_({ ok: true, rows: rows, count: rows.length });
  } catch (err) {
    return json_({ ok: false, error: String(err && err.message ? err.message : err) });
  }
}

/**
 * POST pushes rows, clears a range, or previews.
 *   { secret, action: 'append' | 'overwrite' | 'clear' | 'pull',
 *     sheet: 'Sheet1', rows: [ {...} ], includeHeaders: true, limit: 10 }
 */
function doPost(e) {
  try {
    var body = {};
    if (e && e.postData && e.postData.contents) {
      body = JSON.parse(e.postData.contents);
    }
    authorize_(body);

    var action = String(body.action || 'append');
    var sheetName = body.sheet;

    if (action === 'pull') {
      var pulled = readRows_(sheetName, body.limit);
      return json_({ ok: true, rows: pulled, count: pulled.length });
    }

    var sheet = openSheet_(sheetName);

    if (action === 'clear') {
      sheet.clearContents();
      return json_({ ok: true, action: 'clear', sheet: sheet.getName() });
    }

    var rows = body.rows || [];
    if (!rows.length) {
      return json_({ ok: false, error: 'No rows supplied.' });
    }

    var matrix = toMatrix_(rows, body.includeHeaders);
    if (!matrix.length) {
      return json_({ ok: false, error: 'Rows had no columns.' });
    }

    if (action === 'overwrite') {
      sheet.clearContents();
      sheet.getRange(1, 1, matrix.length, matrix[0].length).setValues(matrix);
    } else {
      // Append below the last row that holds data.
      var startRow = sheet.getLastRow() + 1;
      // Skip the header when the sheet already has content.
      if (startRow > 1 && body.includeHeaders !== false) {
        matrix = matrix.slice(1);
      }
      if (!matrix.length) {
        return json_({ ok: true, action: action, written: 0 });
      }
      sheet.getRange(startRow, 1, matrix.length, matrix[0].length).setValues(matrix);
    }

    return json_({
      ok: true,
      action: action,
      sheet: sheet.getName(),
      written: rows.length
    });
  } catch (err) {
    return json_({ ok: false, error: String(err && err.message ? err.message : err) });
  }
}
`;
}

function driveAppsScript(options: CompanionOptions, secret: string): string {
  const folderId = options.folderId || '';

  return `/**
 * Bernie companion endpoint for Google Drive.
 *
 * Deployed as a Web App, this lists a folder and writes files into it without
 * Bernie holding a Google OAuth token.
 *
 * Generated by Bernie. Safe to edit.
 */

var BERNIE_SECRET = ${JSON.stringify(secret)};
${folderId ? `var FOLDER_ID = ${JSON.stringify(folderId)};` : `// Blank means the script's own Drive root.
var FOLDER_ID = '';`}

function folder_() {
  return FOLDER_ID ? DriveApp.getFolderById(FOLDER_ID) : DriveApp.getRootFolder();
}

function json_(payload) {
  return ContentService
    .createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}

function authorize_(params) {
  if (!BERNIE_SECRET) return;
  if (String(params && params.secret) !== BERNIE_SECRET) {
    throw new Error('Unauthorized: the shared secret did not match.');
  }
}

/** GET lists the folder: ?secret=...&limit=50 */
function doGet(e) {
  try {
    var params = (e && e.parameter) || {};
    authorize_(params);

    var limit = Number(params.limit || 50);
    var files = folder_().getFiles();
    var rows = [];
    while (files.hasNext() && rows.length < limit) {
      var file = files.next();
      rows.push({
        id: file.getId(),
        name: file.getName(),
        mime_type: file.getMimeType(),
        size_bytes: file.getSize(),
        modified_time: file.getLastUpdated().toISOString(),
        link: file.getUrl()
      });
    }
    return json_({ ok: true, rows: rows, count: rows.length });
  } catch (err) {
    return json_({ ok: false, error: String(err && err.message ? err.message : err) });
  }
}

/**
 * POST writes the rows into the folder.
 *   { secret, name: 'export.json', format: 'json' | 'csv', rows: [ {...} ] }
 */
function doPost(e) {
  try {
    var body = {};
    if (e && e.postData && e.postData.contents) {
      body = JSON.parse(e.postData.contents);
    }
    authorize_(body);

    var rows = body.rows || [];
    if (!rows.length) return json_({ ok: false, error: 'No rows supplied.' });

    var format = String(body.format || 'json');
    var name = String(body.name || (format === 'csv' ? 'export.csv' : 'export.json'));

    var contents;
    var mime;
    if (format === 'csv') {
      var headers = [];
      rows.forEach(function (row) {
        Object.keys(row).forEach(function (key) {
          if (headers.indexOf(key) === -1) headers.push(key);
        });
      });
      var lines = [headers.join(',')];
      rows.forEach(function (row) {
        lines.push(headers.map(function (header) {
          var value = row[header];
          if (value === null || value === undefined) value = '';
          return '"' + String(value).replace(/"/g, '""') + '"';
        }).join(','));
      });
      contents = lines.join('\\n');
      mime = MimeType.CSV;
    } else {
      contents = JSON.stringify(rows, null, 2);
      mime = MimeType.PLAIN_TEXT;
    }

    var file = folder_().createFile(name, contents, mime);
    return json_({
      ok: true,
      rows: [{ id: file.getId(), name: file.getName(), link: file.getUrl() }],
      written: rows.length
    });
  } catch (err) {
    return json_({ ok: false, error: String(err && err.message ? err.message : err) });
  }
}
`;
}

/* -------------------------------------------------------------------------- */
/* Supabase, via an Edge Function                                             */
/* -------------------------------------------------------------------------- */

function supabaseEdgeFunction(options: CompanionOptions, secret: string): string {
  const table = options.table || 'rows';
  const onConflict = options.onConflict || '';

  return `/**
 * Bernie companion Edge Function for Supabase.
 *
 * Deploy this and the service role key stays on Supabase's servers: Bernie
 * posts rows to this function, which writes them with elevated rights. That
 * keeps a privileged key out of the browser entirely.
 *
 * Generated by Bernie. Safe to edit.
 */

import { createClient } from 'jsr:@supabase/supabase-js@2';

// Set with: supabase secrets set BERNIE_SECRET=...
const BERNIE_SECRET = Deno.env.get('BERNIE_SECRET') ?? ${JSON.stringify(secret)};

// Injected automatically in the Edge Function runtime.
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const DEFAULT_TABLE = ${JSON.stringify(table)};
const DEFAULT_ON_CONFLICT = ${JSON.stringify(onConflict)};

const client = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

interface RequestBody {
  secret?: string;
  action?: 'insert' | 'upsert' | 'select' | 'update' | 'delete';
  table?: string;
  rows?: Record<string, unknown>[];
  onConflict?: string;
  /** PostgREST-style filters, e.g. { status: 'eq.active' } */
  filters?: Record<string, string>;
  select?: string;
  limit?: number;
  order?: { column: string; ascending?: boolean };
}

function json(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

/** Applies { column: 'op.value' } filters to a PostgREST query builder. */
function applyFilters(query: any, filters?: Record<string, string>) {
  Object.entries(filters ?? {}).forEach(([column, expression]) => {
    const dot = expression.indexOf('.');
    if (dot <= 0) return;
    const op = expression.slice(0, dot);
    const value = expression.slice(dot + 1);
    if (typeof query[op] === 'function') {
      query = query[op](column, value);
    }
  });
  return query;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'content-type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
      },
    });
  }

  if (req.method !== 'POST') {
    return json({ ok: false, error: 'Use POST.' }, 405);
  }

  let body: RequestBody;
  try {
    body = await req.json();
  } catch {
    return json({ ok: false, error: 'Body was not valid JSON.' }, 400);
  }

  if (BERNIE_SECRET && body.secret !== BERNIE_SECRET) {
    return json({ ok: false, error: 'Unauthorized: the shared secret did not match.' }, 401);
  }

  const table = body.table || DEFAULT_TABLE;
  const action = body.action ?? 'insert';

  try {
    if (action === 'select') {
      let query = client.from(table).select(body.select ?? '*');
      query = applyFilters(query, body.filters);
      if (body.order) query = query.order(body.order.column, { ascending: body.order.ascending ?? true });
      if (body.limit) query = query.limit(body.limit);

      const { data, error } = await query;
      if (error) return json({ ok: false, error: error.message }, 400);
      return json({ ok: true, rows: data ?? [], count: data?.length ?? 0 });
    }

    if (action === 'delete') {
      if (!body.filters || Object.keys(body.filters).length === 0) {
        return json({ ok: false, error: 'Refusing to delete without a filter.' }, 400);
      }
      const { data, error } = await applyFilters(client.from(table).delete(), body.filters).select();
      if (error) return json({ ok: false, error: error.message }, 400);
      return json({ ok: true, rows: data ?? [], deleted: data?.length ?? 0 });
    }

    const rows = body.rows ?? [];
    if (rows.length === 0) return json({ ok: false, error: 'No rows supplied.' }, 400);

    if (action === 'update') {
      if (!body.filters || Object.keys(body.filters).length === 0) {
        return json({ ok: false, error: 'Refusing to update without a filter.' }, 400);
      }
      const { data, error } = await applyFilters(client.from(table).update(rows[0]), body.filters).select();
      if (error) return json({ ok: false, error: error.message }, 400);
      return json({ ok: true, rows: data ?? [], updated: data?.length ?? 0 });
    }

    if (action === 'upsert') {
      const onConflict = body.onConflict || DEFAULT_ON_CONFLICT;
      const { data, error } = await client
        .from(table)
        .upsert(rows, onConflict ? { onConflict } : undefined)
        .select();
      if (error) return json({ ok: false, error: error.message }, 400);
      return json({ ok: true, rows: data ?? [], written: data?.length ?? rows.length });
    }

    const { data, error } = await client.from(table).insert(rows).select();
    if (error) return json({ ok: false, error: error.message }, 400);
    return json({ ok: true, rows: data ?? [], written: data?.length ?? rows.length });
  } catch (err) {
    return json({ ok: false, error: err instanceof Error ? err.message : String(err) }, 500);
  }
});
`;
}

/* -------------------------------------------------------------------------- */

/** Builds the deployable bundle for one target. */
export function generateCompanion(target: CompanionTarget, options: CompanionOptions = {}): CompanionBundle {
  const secret = secretOf(options);

  if (target === 'sheets-apps-script') {
    return {
      target,
      title: 'Google Sheets — Apps Script Web App',
      summary:
        'Reads and writes this spreadsheet from an Apps Script Web App, so Bernie needs no Google OAuth token.',
      steps: [
        'Open the spreadsheet, then Extensions, Apps Script.',
        'Replace the contents of Code.gs with the file below and save.',
        'Deploy, New deployment, type Web app.',
        'Set "Execute as" to Me, and "Who has access" to Anyone with the link.',
        'Deploy, authorize when prompted, and copy the /exec Web App URL.',
      ],
      files: [{ name: 'Code.gs', language: 'javascript', contents: sheetsAppsScript(options, secret) }],
      wireUp: [
        'Open Connections & APIs, Custom HTTP Saves.',
        'Paste the /exec URL as the Base URL and save.',
        'On a Custom HTTP node choose Send a request, method POST, and leave the path blank.',
        `Body: {"secret": "${secret}", "action": "append", "sheet": "${options.sheetName || 'Sheet1'}"} — Bernie appends the incoming rows.`,
        'Use "action": "pull" to read rows instead, or "overwrite" to replace the tab.',
      ],
    };
  }

  if (target === 'drive-apps-script') {
    return {
      target,
      title: 'Google Drive — Apps Script Web App',
      summary: 'Lists a Drive folder and writes files into it without Bernie holding a Google token.',
      steps: [
        'Open script.google.com and create a new project.',
        'Replace Code.gs with the file below and save.',
        'Deploy, New deployment, type Web app.',
        'Set "Execute as" to Me, and "Who has access" to Anyone with the link.',
        'Deploy, authorize when prompted, and copy the /exec Web App URL.',
      ],
      files: [{ name: 'Code.gs', language: 'javascript', contents: driveAppsScript(options, secret) }],
      wireUp: [
        'Open Connections & APIs, Custom HTTP Saves, and paste the /exec URL as the Base URL.',
        `To list files, use a Custom HTTP node with method GET and query {"secret": "${secret}", "limit": 50}.`,
        `To write rows, use method POST and body {"secret": "${secret}", "format": "csv"}.`,
      ],
    };
  }

  return {
    target,
    title: 'Supabase — Edge Function',
    summary:
      'Writes rows with the service role key from inside Supabase, so that privileged key never reaches the browser.',
    steps: [
      'Install the CLI and run: supabase functions new bernie-rows',
      'Replace supabase/functions/bernie-rows/index.ts with the file below.',
      `Set the shared secret: supabase secrets set BERNIE_SECRET=${secret}`,
      'Deploy it: supabase functions deploy bernie-rows',
      'Copy the function URL from the dashboard, Edge Functions.',
    ],
    files: [
      { name: 'index.ts', language: 'typescript', contents: supabaseEdgeFunction(options, secret) },
      {
        name: 'deno.json',
        language: 'json',
        contents: JSON.stringify({ imports: { '@supabase/supabase-js': 'jsr:@supabase/supabase-js@2' } }, null, 2),
      },
    ],
    wireUp: [
      'Either use the Supabase node: choose "Invoke an Edge Function" and set the name to bernie-rows.',
      'Or point Custom HTTP Saves at the function URL and POST to it directly.',
      `Body: {"secret": "${secret}", "action": "upsert", "table": "${options.table || 'rows'}"${
        options.onConflict ? `, "onConflict": "${options.onConflict}"` : ''
      }}`,
      'Supported actions: insert, upsert, select, update, delete. update and delete require filters.',
    ],
  };
}

/** The companion targets available for an integration, if any. */
export function companionTargetsFor(integration: string): CompanionTarget[] {
  switch (integration) {
    case 'sheets':
      return ['sheets-apps-script'];
    case 'drive':
      return ['drive-apps-script'];
    case 'supabase':
      return ['supabase-edge-function'];
    default:
      return [];
  }
}
