/**
 * Asana operations, against API v1.0 (https://developers.asana.com/reference).
 *
 * Asana conventions this file encodes:
 *  - every write is wrapped in `{ data: ... }`, and every read returns `data`
 *  - `opt_fields` decides which fields come back; the defaults here match what
 *    `normalizeAsanaTasks` flattens
 *  - collections are scoped: /tasks needs a project, or an assignee plus a
 *    workspace; /projects and /custom_fields hang off a workspace
 */

import { ASANA_OPT_FIELDS } from '../providerRequests';
import { IntegrationOperations, OperationSpec, jsonField, numberField, rawOperation, textField } from './types';

const PROJECT_OPT_FIELDS = 'gid,name,archived,color,created_at,modified_at,notes,public,owner.name,team.name,current_status.text';
const STORY_OPT_FIELDS = 'gid,created_at,created_by.name,text,type,resource_subtype';
const USER_OPT_FIELDS = 'gid,name,email';

const operations: OperationSpec[] = [
  /* ------------------------------- tasks -------------------------------- */
  {
    id: 'tasks.list',
    label: 'List tasks',
    direction: 'pull',
    summary: 'Tasks in a project, or assigned to someone in a workspace.',
    docsUrl: 'https://developers.asana.com/reference/gettasks',
    method: 'GET',
    path: '/tasks',
    query: ['project', 'section', 'assignee', 'workspace', 'completed_since', 'modified_since', 'limit', 'opt_fields'],
    result: 'asanaTasks',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('project', 'Project GID', 'Defaults to the connection setting'),
      textField('section', 'Section GID', 'Optional, narrows to one section'),
      textField('assignee', 'Assignee GID', 'me', 'Requires a workspace GID as well.'),
      textField('workspace', 'Workspace GID'),
      textField('completed_since', 'Completed Since', 'now', 'ISO date, or "now" for incomplete tasks only.'),
      textField('modified_since', 'Modified Since', '2026-01-01T00:00:00Z'),
      numberField('limit', 'Page Size', '100'),
      textField('opt_fields', 'Fields', ASANA_OPT_FIELDS),
    ],
  },
  {
    id: 'tasks.get',
    label: 'Get one task',
    direction: 'pull',
    summary: 'A single task by GID.',
    docsUrl: 'https://developers.asana.com/reference/gettask',
    method: 'GET',
    path: '/tasks/{taskGid}',
    query: ['opt_fields'],
    result: 'asanaTasks',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('taskGid', 'Task GID', '1200000000000001', undefined, true),
      textField('opt_fields', 'Fields', ASANA_OPT_FIELDS),
    ],
  },
  {
    id: 'tasks.create',
    label: 'Create tasks',
    direction: 'push',
    summary: 'Creates one task per incoming row. Row keys become task fields.',
    docsUrl: 'https://developers.asana.com/reference/createtask',
    method: 'POST',
    path: '/tasks',
    body: 'asanaData',
    result: 'asanaTasks',
    resultPath: 'data',
    consumesRows: true,
    emitsRows: true,
    fields: [
      textField('projects', 'Project GID', 'Task is added to this project', 'Applied to every row that does not set its own.'),
      textField('workspace', 'Workspace GID', 'Required when no project is given'),
      textField('assignee', 'Default Assignee GID', 'me'),
    ],
  },
  {
    id: 'tasks.update',
    label: 'Update tasks',
    direction: 'push',
    summary: 'Updates one task per row. Each row needs a gid plus the fields to change.',
    docsUrl: 'https://developers.asana.com/reference/updatetask',
    method: 'PUT',
    path: '/tasks/{taskGid}',
    body: 'asanaData',
    result: 'asanaTasks',
    resultPath: 'data',
    consumesRows: true,
    emitsRows: true,
    fields: [
      textField('taskGid', 'Task GID', 'Falls back to each row’s gid', 'Leave blank to update the task named by each row.'),
    ],
  },
  {
    id: 'tasks.delete',
    label: 'Delete task',
    direction: 'mutate',
    summary: 'Moves a task to the trash.',
    docsUrl: 'https://developers.asana.com/reference/deletetask',
    method: 'DELETE',
    path: '/tasks/{taskGid}',
    result: 'single',
    resultPath: 'data',
    fields: [textField('taskGid', 'Task GID', '1200000000000001', undefined, true)],
  },
  {
    id: 'tasks.search',
    label: 'Search tasks',
    direction: 'pull',
    summary: 'Full-text search across a workspace.',
    docsUrl: 'https://developers.asana.com/reference/searchtasksforworkspace',
    method: 'GET',
    path: '/workspaces/{workspace}/tasks/search',
    query: ['text', 'completed', 'assignee.any', 'projects.any', 'limit', 'opt_fields'],
    result: 'asanaTasks',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('workspace', 'Workspace GID', 'Defaults to the connection setting'),
      textField('text', 'Search Text', 'billing', undefined, true),
      {
        key: 'completed',
        label: 'Completed',
        type: 'select',
        options: [
          { value: 'false', label: 'Incomplete only' },
          { value: 'true', label: 'Completed only' },
        ],
      },
      textField('assignee.any', 'Assignee GIDs', 'Comma separated'),
      textField('projects.any', 'Project GIDs', 'Comma separated'),
      numberField('limit', 'Page Size', '50'),
      textField('opt_fields', 'Fields', ASANA_OPT_FIELDS),
    ],
  },
  {
    id: 'tasks.subtasks',
    label: 'List subtasks',
    direction: 'pull',
    summary: 'Subtasks of one task.',
    docsUrl: 'https://developers.asana.com/reference/getsubtasksfortask',
    method: 'GET',
    path: '/tasks/{taskGid}/subtasks',
    query: ['limit', 'opt_fields'],
    result: 'asanaTasks',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('taskGid', 'Parent Task GID', '1200000000000001', undefined, true),
      numberField('limit', 'Page Size', '100'),
      textField('opt_fields', 'Fields', ASANA_OPT_FIELDS),
    ],
  },
  {
    id: 'tasks.addSubtask',
    label: 'Add subtask',
    direction: 'mutate',
    summary: 'Creates a subtask under a task.',
    docsUrl: 'https://developers.asana.com/reference/createsubtaskfortask',
    method: 'POST',
    path: '/tasks/{taskGid}/subtasks',
    body: 'asanaData',
    result: 'asanaTasks',
    resultPath: 'data',
    fields: [
      textField('taskGid', 'Parent Task GID', '1200000000000001', undefined, true),
      textField('name', 'Subtask Name', 'Follow up', undefined, true),
      textField('notes', 'Notes'),
    ],
  },
  {
    id: 'tasks.comments',
    label: 'List comments',
    direction: 'pull',
    summary: 'The story feed on a task, including comments.',
    docsUrl: 'https://developers.asana.com/reference/getstoriesfortask',
    method: 'GET',
    path: '/tasks/{taskGid}/stories',
    query: ['limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('taskGid', 'Task GID', '1200000000000001', undefined, true),
      numberField('limit', 'Page Size', '50'),
      textField('opt_fields', 'Fields', STORY_OPT_FIELDS),
    ],
  },
  {
    id: 'tasks.addComment',
    label: 'Add comment',
    direction: 'mutate',
    summary: 'Posts a comment on a task.',
    docsUrl: 'https://developers.asana.com/reference/createstoryfortask',
    method: 'POST',
    path: '/tasks/{taskGid}/stories',
    body: 'asanaData',
    result: 'single',
    resultPath: 'data',
    fields: [
      textField('taskGid', 'Task GID', '1200000000000001', undefined, true),
      jsonField('text', 'Comment', 'Shipped in build 42'),
    ],
  },
  {
    id: 'tasks.addToProject',
    label: 'Add task to project',
    direction: 'mutate',
    summary: 'Puts an existing task into a project, optionally in a section.',
    docsUrl: 'https://developers.asana.com/reference/addprojectfortask',
    method: 'POST',
    path: '/tasks/{taskGid}/addProject',
    body: 'asanaData',
    result: 'single',
    resultPath: 'data',
    fields: [
      textField('taskGid', 'Task GID', undefined, undefined, true),
      textField('project', 'Project GID', undefined, undefined, true),
      textField('section', 'Section GID'),
    ],
  },
  {
    id: 'tasks.addTag',
    label: 'Add tag to task',
    direction: 'mutate',
    summary: 'Tags an existing task.',
    docsUrl: 'https://developers.asana.com/reference/addtagfortask',
    method: 'POST',
    path: '/tasks/{taskGid}/addTag',
    body: 'asanaData',
    result: 'single',
    resultPath: 'data',
    fields: [
      textField('taskGid', 'Task GID', undefined, undefined, true),
      textField('tag', 'Tag GID', undefined, undefined, true),
    ],
  },

  /* ------------------------------ projects ------------------------------ */
  {
    id: 'projects.list',
    label: 'List projects',
    direction: 'pull',
    summary: 'Projects in a workspace or team.',
    docsUrl: 'https://developers.asana.com/reference/getprojects',
    method: 'GET',
    path: '/projects',
    query: ['workspace', 'team', 'archived', 'limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('workspace', 'Workspace GID', 'Defaults to the connection setting'),
      textField('team', 'Team GID'),
      {
        key: 'archived',
        label: 'Archived',
        type: 'select',
        options: [
          { value: 'false', label: 'Active only' },
          { value: 'true', label: 'Archived only' },
        ],
      },
      numberField('limit', 'Page Size', '100'),
      textField('opt_fields', 'Fields', PROJECT_OPT_FIELDS),
    ],
  },
  {
    id: 'projects.get',
    label: 'Get one project',
    direction: 'pull',
    summary: 'A single project by GID.',
    docsUrl: 'https://developers.asana.com/reference/getproject',
    method: 'GET',
    path: '/projects/{projectGid}',
    query: ['opt_fields'],
    result: 'single',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('projectGid', 'Project GID', undefined, undefined, true),
      textField('opt_fields', 'Fields', PROJECT_OPT_FIELDS),
    ],
  },
  {
    id: 'projects.create',
    label: 'Create project',
    direction: 'mutate',
    summary: 'Creates a project in a workspace.',
    docsUrl: 'https://developers.asana.com/reference/createproject',
    method: 'POST',
    path: '/projects',
    body: 'asanaData',
    result: 'single',
    resultPath: 'data',
    fields: [
      textField('name', 'Project Name', 'Q4 launch', undefined, true),
      textField('workspace', 'Workspace GID', 'Defaults to the connection setting'),
      textField('team', 'Team GID', undefined, 'Required in an organization.'),
      jsonField('notes', 'Notes'),
    ],
  },
  {
    id: 'projects.tasks',
    label: 'List project tasks',
    direction: 'pull',
    summary: 'Tasks belonging to one project.',
    docsUrl: 'https://developers.asana.com/reference/gettasksforproject',
    method: 'GET',
    path: '/projects/{projectGid}/tasks',
    query: ['limit', 'opt_fields'],
    result: 'asanaTasks',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('projectGid', 'Project GID', 'Defaults to the connection setting'),
      numberField('limit', 'Page Size', '100'),
      textField('opt_fields', 'Fields', ASANA_OPT_FIELDS),
    ],
  },
  {
    id: 'projects.sections',
    label: 'List sections',
    direction: 'pull',
    summary: 'Sections (columns) in a project.',
    docsUrl: 'https://developers.asana.com/reference/getsectionsforproject',
    method: 'GET',
    path: '/projects/{projectGid}/sections',
    query: ['limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('projectGid', 'Project GID', 'Defaults to the connection setting'),
      numberField('limit', 'Page Size', '100'),
      textField('opt_fields', 'Fields', 'gid,name,created_at'),
    ],
  },

  /* ------------------------- workspace metadata ------------------------- */
  {
    id: 'workspaces.list',
    label: 'List workspaces',
    direction: 'pull',
    summary: 'Workspaces the token can see. Use this to find your workspace GID.',
    docsUrl: 'https://developers.asana.com/reference/getworkspaces',
    method: 'GET',
    path: '/workspaces',
    query: ['limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [textField('opt_fields', 'Fields', 'gid,name,is_organization')],
  },
  {
    id: 'users.me',
    label: 'Get my user',
    direction: 'pull',
    summary: 'The authenticated user. Handy for checking a token.',
    docsUrl: 'https://developers.asana.com/reference/getuser',
    method: 'GET',
    path: '/users/me',
    query: ['opt_fields'],
    result: 'single',
    resultPath: 'data',
    emitsRows: true,
    fields: [textField('opt_fields', 'Fields', `${USER_OPT_FIELDS},workspaces.name`)],
  },
  {
    id: 'users.list',
    label: 'List users',
    direction: 'pull',
    summary: 'Users in a workspace or team.',
    docsUrl: 'https://developers.asana.com/reference/getusers',
    method: 'GET',
    path: '/users',
    query: ['workspace', 'team', 'limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('workspace', 'Workspace GID', 'Defaults to the connection setting'),
      textField('team', 'Team GID'),
      textField('opt_fields', 'Fields', USER_OPT_FIELDS),
    ],
  },
  {
    id: 'teams.list',
    label: 'List teams',
    direction: 'pull',
    summary: 'Teams in an organization.',
    docsUrl: 'https://developers.asana.com/reference/getteamsforworkspace',
    method: 'GET',
    path: '/workspaces/{workspace}/teams',
    query: ['limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('workspace', 'Workspace GID', 'Defaults to the connection setting'),
      textField('opt_fields', 'Fields', 'gid,name,description'),
    ],
  },
  {
    id: 'tags.list',
    label: 'List tags',
    direction: 'pull',
    summary: 'Tags in a workspace.',
    docsUrl: 'https://developers.asana.com/reference/gettags',
    method: 'GET',
    path: '/tags',
    query: ['workspace', 'limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('workspace', 'Workspace GID', 'Defaults to the connection setting'),
      textField('opt_fields', 'Fields', 'gid,name,color'),
    ],
  },
  {
    id: 'customFields.list',
    label: 'List custom fields',
    direction: 'pull',
    summary: 'Custom field definitions in a workspace.',
    docsUrl: 'https://developers.asana.com/reference/getcustomfieldsforworkspace',
    method: 'GET',
    path: '/workspaces/{workspace}/custom_fields',
    query: ['limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('workspace', 'Workspace GID', 'Defaults to the connection setting'),
      textField('opt_fields', 'Fields', 'gid,name,type,enum_options.name'),
    ],
  },
  {
    id: 'attachments.list',
    label: 'List attachments',
    direction: 'pull',
    summary: 'Attachments on a task.',
    docsUrl: 'https://developers.asana.com/reference/getattachmentsforobject',
    method: 'GET',
    path: '/attachments',
    query: ['parent', 'limit', 'opt_fields'],
    result: 'rows',
    resultPath: 'data',
    emitsRows: true,
    fields: [
      textField('parent', 'Task GID', undefined, undefined, true),
      textField('opt_fields', 'Fields', 'gid,name,download_url,created_at'),
    ],
  },
  rawOperation('https://developers.asana.com/reference/rest-api-reference', '/portfolios'),
];

export const asanaOperations: IntegrationOperations = {
  integration: 'asana',
  defaultOperation: 'tasks.list',
  operations,
};
