/**
 * Supabase, Keepa and GitHub operations.
 *
 * Supabase goes through PostgREST, where filters are query parameters shaped
 * `column=op.value` (e.g. `status=eq.active`), writes are JSON arrays, and the
 * `Prefer` header decides whether rows come back and how conflicts resolve.
 */

import { KEEPA_DOMAINS } from '../integrationCore';
import { IntegrationOperations, OperationSpec, jsonField, numberField, rawOperation, textField } from './types';

const FILTER_HELP = 'PostgREST filters, one per line: status=eq.active';

const supabaseOps: OperationSpec[] = [
  {
    id: 'rows.select',
    label: 'Pull from table',
    direction: 'pull',
    summary: 'Selects rows, with optional filters, ordering and a limit.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/tables_views.html',
    method: 'GET',
    path: '/rest/v1/{table}',
    result: 'rows',
    emitsRows: true,
    custom: 'supabase.select',
    fields: [
      textField('table', 'Table', 'Defaults to the connection setting'),
      textField('select', 'Columns', '*', 'Comma separated, or * for all. Supports embeds: *,orders(*)'),
      jsonField('filters', 'Filters', 'status=eq.active\nprice=gt.10', FILTER_HELP),
      textField('order', 'Order By', 'created_at.desc'),
      numberField('limit', 'Limit', '100'),
      numberField('offset', 'Offset', '0'),
    ],
  },
  {
    id: 'rows.preview',
    label: 'Preview rows',
    direction: 'preview',
    summary: 'Selects a capped sample so you can check the columns before writing.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/tables_views.html',
    method: 'GET',
    path: '/rest/v1/{table}',
    result: 'rows',
    emitsRows: true,
    custom: 'supabase.select',
    fields: [
      textField('table', 'Table', 'Defaults to the connection setting'),
      numberField('limit', 'Rows To Preview', '10'),
    ],
  },
  {
    id: 'rows.insert',
    label: 'Push to table (insert)',
    direction: 'push',
    summary: 'Inserts the incoming rows. Fails on a duplicate key.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/tables_views.html#insert',
    method: 'POST',
    path: '/rest/v1/{table}',
    body: 'rows',
    result: 'rows',
    consumesRows: true,
    emitsRows: true,
    custom: 'supabase.write',
    fields: [textField('table', 'Table', 'Defaults to the connection setting')],
  },
  {
    id: 'rows.upsert',
    label: 'Push to table (upsert)',
    direction: 'push',
    summary: 'Inserts the rows, merging duplicates on the conflict column.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/tables_views.html#upsert',
    method: 'POST',
    path: '/rest/v1/{table}',
    body: 'rows',
    result: 'rows',
    consumesRows: true,
    emitsRows: true,
    custom: 'supabase.write',
    fields: [
      textField('table', 'Table', 'Defaults to the connection setting'),
      textField('onConflict', 'On Conflict Column(s)', 'id', 'Comma separated. Required to merge.'),
    ],
  },
  {
    id: 'rows.update',
    label: 'Update rows',
    direction: 'push',
    summary: 'Patches the rows matching the filters with the first input row.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/tables_views.html#update',
    method: 'PATCH',
    path: '/rest/v1/{table}',
    body: 'rows',
    result: 'rows',
    consumesRows: true,
    emitsRows: true,
    custom: 'supabase.write',
    fields: [
      textField('table', 'Table', 'Defaults to the connection setting'),
      jsonField('filters', 'Filters', 'id=eq.42', `${FILTER_HELP} Required, to avoid touching every row.`),
    ],
  },
  {
    id: 'rows.delete',
    label: 'Delete rows',
    direction: 'mutate',
    summary: 'Deletes the rows matching the filters.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/tables_views.html#delete',
    method: 'DELETE',
    path: '/rest/v1/{table}',
    result: 'rows',
    emitsRows: true,
    custom: 'supabase.write',
    fields: [
      textField('table', 'Table', 'Defaults to the connection setting'),
      jsonField('filters', 'Filters', 'id=eq.42', `${FILTER_HELP} Required, to avoid deleting every row.`),
    ],
  },
  {
    id: 'rows.count',
    label: 'Count rows',
    direction: 'pull',
    summary: 'Returns how many rows match, without fetching them.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/pagination_count.html',
    method: 'GET',
    path: '/rest/v1/{table}',
    result: 'single',
    emitsRows: true,
    custom: 'supabase.count',
    fields: [
      textField('table', 'Table', 'Defaults to the connection setting'),
      jsonField('filters', 'Filters', 'status=eq.active', FILTER_HELP),
    ],
  },
  {
    id: 'rpc.call',
    label: 'Call a function (RPC)',
    direction: 'mutate',
    summary: 'Invokes a Postgres function with JSON arguments.',
    docsUrl: 'https://postgrest.org/en/stable/references/api/functions.html',
    method: 'POST',
    path: '/rest/v1/rpc/{fn}',
    body: 'rawBody',
    result: 'passthrough',
    emitsRows: true,
    fields: [
      textField('fn', 'Function Name', 'recalculate_totals', undefined, true),
      jsonField('rawBody', 'Arguments (JSON)', '{"days": 30}'),
    ],
  },
  {
    id: 'functions.invoke',
    label: 'Invoke an Edge Function',
    direction: 'push',
    summary: 'Posts the incoming rows to one of your Supabase Edge Functions.',
    docsUrl: 'https://supabase.com/docs/guides/functions',
    method: 'POST',
    path: '/functions/v1/{fn}',
    body: 'rows',
    result: 'passthrough',
    consumesRows: true,
    emitsRows: true,
    fields: [textField('fn', 'Function Name', 'ingest-rows', undefined, true)],
  },
  rawOperation('https://supabase.com/docs/guides/api', '/rest/v1/products'),
];

export const supabaseOperations: IntegrationOperations = {
  integration: 'supabase',
  defaultOperation: 'rows.select',
  operations: supabaseOps,
};

const keepaOps: OperationSpec[] = [
  {
    id: 'product.lookup',
    label: 'Pull products by ASIN',
    direction: 'pull',
    summary: 'Product data, pricing and sales rank for a list of ASINs.',
    docsUrl: 'https://keepa.com/#!discuss/t/product-object/116',
    method: 'GET',
    path: '/product',
    result: 'keepaProducts',
    emitsRows: true,
    custom: 'keepa.product',
    fields: [
      jsonField('asins', 'ASINs', 'B08N5WRWNW, B07FZ8S74R', 'Comma or newline separated. Up to 100 per call.'),
      { key: 'domain', label: 'Marketplace', type: 'select', options: KEEPA_DOMAINS },
      numberField('stats', 'Stats Window (days)', '30'),
      { key: 'history', label: 'Include full price history', type: 'checkbox' },
      {
        key: 'mergeInputRows',
        label: 'Keep the columns of the incoming rows',
        type: 'checkbox',
        help: 'Merges each ASIN’s Keepa fields into the row it came from, so upstream context survives. Keepa fields win on a name clash.',
      },
    ],
  },
  {
    id: 'product.search',
    label: 'Search products',
    direction: 'pull',
    summary: 'Keyword search against the Amazon catalogue.',
    docsUrl: 'https://keepa.com/#!discuss/t/search-for-products/109',
    method: 'GET',
    path: '/search',
    query: ['term', 'domain', 'page'],
    result: 'keepaProducts',
    resultPath: 'products',
    emitsRows: true,
    fields: [
      textField('term', 'Search Term', 'wireless mouse', undefined, true),
      { key: 'domain', label: 'Marketplace', type: 'select', options: KEEPA_DOMAINS },
      numberField('page', 'Page', '0'),
    ],
  },
  {
    id: 'bestsellers.list',
    label: 'Pull best sellers',
    direction: 'pull',
    summary: 'The best seller ASIN list for a category.',
    docsUrl: 'https://keepa.com/#!discuss/t/best-sellers/1298',
    method: 'GET',
    path: '/bestsellers',
    query: ['category', 'domain'],
    result: 'passthrough',
    emitsRows: true,
    fields: [
      textField('category', 'Category ID', '493964', undefined, true),
      { key: 'domain', label: 'Marketplace', type: 'select', options: KEEPA_DOMAINS },
    ],
  },
  {
    id: 'deals.list',
    label: 'Pull deals',
    direction: 'pull',
    summary: 'Current deals matching a JSON selection object.',
    docsUrl: 'https://keepa.com/#!discuss/t/deals/338',
    method: 'POST',
    path: '/deal',
    body: 'rawBody',
    result: 'passthrough',
    emitsRows: true,
    fields: [
      jsonField('rawBody', 'Deal Selection (JSON)', '{"page": 0, "domainId": 1, "priceTypes": [0]}'),
    ],
  },
  {
    id: 'token.status',
    label: 'Check token balance',
    direction: 'pull',
    summary: 'How many API tokens are left on the key.',
    docsUrl: 'https://keepa.com/#!discuss/t/request-tokens/833',
    method: 'GET',
    path: '/token',
    result: 'single',
    emitsRows: true,
  },
  rawOperation('https://keepa.com/#!discuss/t/api-documentation/1', '/category'),
];

export const keepaOperations: IntegrationOperations = {
  integration: 'keepa',
  defaultOperation: 'product.lookup',
  operations: keepaOps,
};

const githubOps: OperationSpec[] = [
  {
    id: 'issues.list',
    label: 'Pull issues',
    direction: 'pull',
    summary: 'Issues on a repository.',
    docsUrl: 'https://docs.github.com/rest/issues/issues#list-repository-issues',
    method: 'GET',
    path: '/repos/{owner}/{repo}/issues',
    query: ['state', 'labels', 'assignee', 'since', 'per_page'],
    result: 'rows',
    emitsRows: true,
    custom: 'github.issues',
    fields: [
      textField('owner', 'Owner', 'Defaults to the connection setting'),
      textField('repo', 'Repository', 'Defaults to the connection setting'),
      {
        key: 'state',
        label: 'State',
        type: 'select',
        options: [
          { value: 'open', label: 'Open' },
          { value: 'closed', label: 'Closed' },
          { value: 'all', label: 'All' },
        ],
      },
      textField('labels', 'Labels', 'bug,p1'),
      textField('assignee', 'Assignee', 'octocat'),
      numberField('per_page', 'Page Size', '50'),
    ],
  },
  {
    id: 'issues.create',
    label: 'Create issues',
    direction: 'push',
    summary: 'Creates one issue per incoming row (title, body, labels).',
    docsUrl: 'https://docs.github.com/rest/issues/issues#create-an-issue',
    method: 'POST',
    path: '/repos/{owner}/{repo}/issues',
    body: 'rows',
    result: 'rows',
    consumesRows: true,
    emitsRows: true,
    custom: 'github.createIssues',
    fields: [
      textField('owner', 'Owner', 'Defaults to the connection setting'),
      textField('repo', 'Repository', 'Defaults to the connection setting'),
    ],
  },
  {
    id: 'issues.comment',
    label: 'Comment on issue',
    direction: 'mutate',
    summary: 'Adds a comment to one issue or pull request.',
    docsUrl: 'https://docs.github.com/rest/issues/comments#create-an-issue-comment',
    method: 'POST',
    path: '/repos/{owner}/{repo}/issues/{issue_number}/comments',
    body: 'rawBody',
    result: 'single',
    fields: [
      textField('owner', 'Owner', 'Defaults to the connection setting'),
      textField('repo', 'Repository', 'Defaults to the connection setting'),
      textField('issue_number', 'Issue Number', '42', undefined, true),
      jsonField('rawBody', 'Comment (JSON)', '{"body": "Shipped in build 42"}'),
    ],
  },
  {
    id: 'pulls.list',
    label: 'Pull requests',
    direction: 'pull',
    summary: 'Pull requests on a repository.',
    docsUrl: 'https://docs.github.com/rest/pulls/pulls#list-pull-requests',
    method: 'GET',
    path: '/repos/{owner}/{repo}/pulls',
    query: ['state', 'per_page'],
    result: 'rows',
    emitsRows: true,
    custom: 'github.pulls',
    fields: [
      textField('owner', 'Owner', 'Defaults to the connection setting'),
      textField('repo', 'Repository', 'Defaults to the connection setting'),
      {
        key: 'state',
        label: 'State',
        type: 'select',
        options: [
          { value: 'open', label: 'Open' },
          { value: 'closed', label: 'Closed' },
          { value: 'all', label: 'All' },
        ],
      },
      numberField('per_page', 'Page Size', '50'),
    ],
  },
  {
    id: 'repos.list',
    label: 'List repositories',
    direction: 'pull',
    summary: 'Repositories the token can see.',
    docsUrl: 'https://docs.github.com/rest/repos/repos#list-repositories-for-the-authenticated-user',
    method: 'GET',
    path: '/user/repos',
    query: ['affiliation', 'sort', 'per_page'],
    result: 'rows',
    emitsRows: true,
    custom: 'github.repos',
    fields: [numberField('per_page', 'Page Size', '50')],
  },
  {
    id: 'contents.get',
    label: 'Pull file content',
    direction: 'pull',
    summary: 'Reads a file from a repository and decodes it.',
    docsUrl: 'https://docs.github.com/rest/repos/contents#get-repository-content',
    method: 'GET',
    path: '/repos/{owner}/{repo}/contents/{filePath}',
    query: ['ref'],
    result: 'passthrough',
    emitsRows: true,
    custom: 'github.content',
    fields: [
      textField('owner', 'Owner', 'Defaults to the connection setting'),
      textField('repo', 'Repository', 'Defaults to the connection setting'),
      textField('filePath', 'File Path', 'package.json', undefined, true),
      textField('ref', 'Branch Or SHA', 'main'),
    ],
  },
  {
    id: 'workflows.dispatch',
    label: 'Trigger a workflow',
    direction: 'mutate',
    summary: 'Fires a workflow_dispatch event on a branch.',
    docsUrl: 'https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event',
    method: 'POST',
    path: '/repos/{owner}/{repo}/actions/workflows/{workflowId}/dispatches',
    body: 'rawBody',
    result: 'single',
    fields: [
      textField('owner', 'Owner', 'Defaults to the connection setting'),
      textField('repo', 'Repository', 'Defaults to the connection setting'),
      textField('workflowId', 'Workflow File Or ID', 'ci.yml', undefined, true),
      jsonField('rawBody', 'Payload (JSON)', '{"ref": "main"}'),
    ],
  },
  rawOperation('https://docs.github.com/rest', '/user'),
];

export const githubOperations: IntegrationOperations = {
  integration: 'github',
  defaultOperation: 'issues.list',
  operations: githubOps,
};
