/**
 * Google Sheets and Drive operations, against the v4 / v3 REST APIs. Both
 * authorize with the Google token from Supabase sign-in, or with a companion
 * Apps Script deployment when Workspace OAuth is not available.
 */

import { IntegrationOperations, OperationSpec, jsonField, numberField, rawOperation, textField } from './types';

const RANGE_HELP = 'A1 notation. A bare tab name means the whole tab, e.g. Sheet1 or Sheet1!A1:D50.';

const sheetsOps: OperationSpec[] = [
  {
    id: 'values.pull',
    label: 'Pull data',
    direction: 'pull',
    summary: 'Reads a range and emits one row per sheet row, using the header row for keys.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get',
    method: 'GET',
    path: '/v4/spreadsheets/{spreadsheetId}/values/{range}',
    query: ['majorDimension', 'valueRenderOption'],
    result: 'sheetValues',
    emitsRows: true,
    fields: [
      textField('spreadsheetId', 'Spreadsheet ID', 'Defaults to the connection setting'),
      textField('range', 'Range', 'Sheet1', RANGE_HELP),
      {
        key: 'headerRow',
        label: 'First row holds the column names',
        type: 'checkbox',
        help: 'Uncheck to emit positional keys (col_1, col_2, ...).',
      },
      {
        key: 'valueRenderOption',
        label: 'Value Rendering',
        type: 'select',
        options: [
          { value: 'FORMATTED_VALUE', label: 'As displayed' },
          { value: 'UNFORMATTED_VALUE', label: 'Raw values' },
          { value: 'FORMULA', label: 'Formulas' },
        ],
      },
    ],
  },
  {
    id: 'values.preview',
    label: 'Preview rows',
    direction: 'preview',
    summary: 'Reads a capped sample so you can inspect the shape before writing.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get',
    method: 'GET',
    path: '/v4/spreadsheets/{spreadsheetId}/values/{range}',
    query: ['valueRenderOption'],
    result: 'sheetValues',
    emitsRows: true,
    custom: 'sheets.preview',
    fields: [
      textField('spreadsheetId', 'Spreadsheet ID', 'Defaults to the connection setting'),
      textField('range', 'Range', 'Sheet1', RANGE_HELP),
      numberField('previewRows', 'Rows To Preview', '10'),
      { key: 'headerRow', label: 'First row holds the column names', type: 'checkbox' },
    ],
  },
  {
    id: 'values.append',
    label: 'Push data (append)',
    direction: 'push',
    summary: 'Appends the incoming rows below whatever is already in the tab.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append',
    method: 'POST',
    path: '/v4/spreadsheets/{spreadsheetId}/values/{range}:append',
    query: ['valueInputOption', 'insertDataOption'],
    body: 'sheetValues',
    result: 'single',
    consumesRows: true,
    fields: [
      textField('spreadsheetId', 'Spreadsheet ID', 'Defaults to the connection setting'),
      textField('range', 'Range', 'Sheet1', RANGE_HELP),
      { key: 'includeHeaders', label: 'Write a header row', type: 'checkbox' },
    ],
  },
  {
    id: 'values.update',
    label: 'Push data (overwrite)',
    direction: 'push',
    summary: 'Overwrites the range starting at its top-left cell.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update',
    method: 'PUT',
    path: '/v4/spreadsheets/{spreadsheetId}/values/{range}',
    query: ['valueInputOption'],
    body: 'sheetValues',
    result: 'single',
    consumesRows: true,
    fields: [
      textField('spreadsheetId', 'Spreadsheet ID', 'Defaults to the connection setting'),
      textField('range', 'Range', 'Sheet1!A1', RANGE_HELP),
      { key: 'includeHeaders', label: 'Write a header row', type: 'checkbox' },
    ],
  },
  {
    id: 'values.clear',
    label: 'Clear range',
    direction: 'mutate',
    summary: 'Empties a range, keeping the formatting.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/clear',
    method: 'POST',
    path: '/v4/spreadsheets/{spreadsheetId}/values/{range}:clear',
    body: 'none',
    result: 'single',
    fields: [
      textField('spreadsheetId', 'Spreadsheet ID', 'Defaults to the connection setting'),
      textField('range', 'Range', 'Sheet1!A2:Z', RANGE_HELP),
    ],
  },
  {
    id: 'sheets.metadata',
    label: 'List tabs',
    direction: 'pull',
    summary: 'The tabs in a spreadsheet, with their sizes. Use it to find tab names.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get',
    method: 'GET',
    path: '/v4/spreadsheets/{spreadsheetId}',
    query: ['fields'],
    result: 'rows',
    emitsRows: true,
    custom: 'sheets.metadata',
    fields: [textField('spreadsheetId', 'Spreadsheet ID', 'Defaults to the connection setting')],
  },
  {
    id: 'sheets.addTab',
    label: 'Add tab',
    direction: 'mutate',
    summary: 'Adds a new tab to the spreadsheet.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/batchUpdate',
    method: 'POST',
    path: '/v4/spreadsheets/{spreadsheetId}:batchUpdate',
    body: 'rawBody',
    result: 'single',
    custom: 'sheets.addTab',
    fields: [
      textField('spreadsheetId', 'Spreadsheet ID', 'Defaults to the connection setting'),
      textField('title', 'Tab Name', 'Imported', undefined, true),
    ],
  },
  {
    id: 'sheets.create',
    label: 'Create spreadsheet',
    direction: 'mutate',
    summary: 'Creates a new spreadsheet and returns its ID.',
    docsUrl: 'https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/create',
    method: 'POST',
    path: '/v4/spreadsheets',
    body: 'rawBody',
    result: 'single',
    custom: 'sheets.create',
    fields: [textField('title', 'Title', 'Bernie export', undefined, true)],
  },
  rawOperation(
    'https://developers.google.com/sheets/api/reference/rest',
    '/v4/spreadsheets/{id}/values/Sheet1'
  ),
];

export const sheetsOperations: IntegrationOperations = {
  integration: 'sheets',
  defaultOperation: 'values.pull',
  operations: sheetsOps,
};

const driveOps: OperationSpec[] = [
  {
    id: 'files.list',
    label: 'List files',
    direction: 'pull',
    summary: 'Files in the configured folder, newest first.',
    docsUrl: 'https://developers.google.com/drive/api/reference/rest/v3/files/list',
    method: 'GET',
    path: '/drive/v3/files',
    query: ['q', 'pageSize', 'orderBy', 'fields'],
    result: 'driveFiles',
    emitsRows: true,
    custom: 'drive.list',
    fields: [
      textField('folderId', 'Folder ID', 'Defaults to the connection setting'),
      textField('nameContains', 'Name Contains', 'invoice'),
      textField('mimeType', 'MIME Type', 'application/pdf'),
      numberField('pageSize', 'Max Files', '25'),
    ],
  },
  {
    id: 'files.get',
    label: 'Pull file content',
    direction: 'pull',
    summary: 'Downloads one file. JSON and CSV are parsed into rows.',
    docsUrl: 'https://developers.google.com/drive/api/reference/rest/v3/files/get',
    method: 'GET',
    path: '/drive/v3/files/{fileId}',
    query: ['alt'],
    result: 'passthrough',
    emitsRows: true,
    custom: 'drive.get',
    fields: [textField('fileId', 'File ID', undefined, undefined, true)],
  },
  {
    id: 'files.upload',
    label: 'Push rows to a file',
    direction: 'push',
    summary: 'Writes the incoming rows into the folder as JSON or CSV.',
    docsUrl: 'https://developers.google.com/drive/api/guides/manage-uploads',
    method: 'POST',
    path: '/upload/drive/v3/files',
    body: 'rows',
    result: 'single',
    consumesRows: true,
    custom: 'drive.upload',
    fields: [
      textField('name', 'File Name', 'export.json'),
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        options: [
          { value: 'json', label: 'JSON' },
          { value: 'csv', label: 'CSV' },
        ],
      },
      textField('folderId', 'Folder ID', 'Defaults to the connection setting'),
    ],
  },
  {
    id: 'files.createFolder',
    label: 'Create folder',
    direction: 'mutate',
    summary: 'Creates a folder, optionally inside the configured one.',
    docsUrl: 'https://developers.google.com/drive/api/guides/folder',
    method: 'POST',
    path: '/drive/v3/files',
    body: 'rawBody',
    result: 'single',
    custom: 'drive.createFolder',
    fields: [
      textField('name', 'Folder Name', 'Exports', undefined, true),
      textField('folderId', 'Parent Folder ID', 'Defaults to the connection setting'),
    ],
  },
  {
    id: 'files.trash',
    label: 'Trash file',
    direction: 'mutate',
    summary: 'Moves a file to the Drive trash.',
    docsUrl: 'https://developers.google.com/drive/api/reference/rest/v3/files/update',
    method: 'PATCH',
    path: '/drive/v3/files/{fileId}',
    body: 'rawBody',
    result: 'single',
    custom: 'drive.trash',
    fields: [textField('fileId', 'File ID', undefined, undefined, true)],
  },
  rawOperation('https://developers.google.com/drive/api/reference/rest/v3', '/drive/v3/about'),
];

export const driveOperations: IntegrationOperations = {
  integration: 'drive',
  defaultOperation: 'files.list',
  operations: driveOps,
};
